### ISSUE TITLE
Ability to display multiple locale fields at once?

### ISSUE THREAD

**Issue by purplespider** [tractorcow/silverstripe-fluent#209]
In some situations, it's much nicer to display all the locale fields at once, instead of having to save the record and switch the locale via the menu dropdown.

**e.g. A simple "Category" object (mockup):**
![](http://spdr.me/a6oE+)

Is this easily possible?

**Comment by phptek** [comment]
@purplespider My 2c worth is that this would not be "easily" possible by virtue of the fact that CMS locale editing is done using a single value on a single CMS cookie called `FluentLocale_CMS`, indeed the whole module is predicated on a single translation basis.

Having said that and thinking for 30s, there's no reason technically that several locales couldn't be stored at once as a serialized array in the `FluentLocale_CMS` cookie, but the LHS locale selector menu UI would need to be re-done (with radio buttons or some such) and a lot of the backend logic that bases itself on a single locale, would have t be refactored.

But then I'm not the author, and this really is my 2c worth :-)

**Comment by tractorcow** [comment]
Yep, you can add fields manually for each of the locale versions. When a record is loaded, it actually does store the field value for ALL locales under the locale-suffixed versions.

E.g.

```php
$fields->addFieldsToTab('Content', array(
	new TextField('Content'),
	new TextField('Content_en_NZ'),
	new TextField('Content_mi_NZ'),
));
```

However it wouldn't be easy to write back without some manual hacking, since the "Field" is always written back to "Field_current_locale" on save. You can probably hack your display logic to always substitute `Field` for `Field_current_locale` where applicable.

**Comment by purplespider** [comment]
Thanks for clarifying what would be involved. Think I'll give it a miss for the time being, may look into it at some point though as I've come across as few use cases where it would make things much easier for the user.

**Comment by tractorcow** [comment]
I guess this issue is more a question than a bug, so I guess it's been answered? :P
