### ISSUE TITLE
Disabling translate on sub-class

### ISSUE THREAD

**Issue by cwchong** [tractorcow/silverstripe-fluent#248]
Hi, I have a use-case where "NewsArticlePage", a sub-class of Page needs to be have translation turned off.
However, since, I am guessing, the translatable fields (Title, Content) are included via the parent SiteTree class, adding 
private static $translate = 'none';
to the "NewsArticlePage" does not disable translation on the Title/Content fields.

Is there a way to do so?

**Comment by phptek** [comment]
One thing springs to mind is that the Fluent extension sounds like it's  applied to Page, hence your pagetype inheriting some translated fields. What about applying the extension to just the types you want, and not all of them via Page? Im not in front of a machine right now, so there may be a better way of doing it.

**Comment by cwchong** [comment]
unfortunately, i believe Fluent is being applied to SiteTree instead (since Title/Content are defined there), and I would like not to reinvent SiteTree along with its functionalities where possible.

**Comment by tractorcow** [comment]
Sorry, from what I understand it's not possible to tell fluent not to translate some classes. The reason is that localisation is on a table-by-table basis, and it can't easily tell which class a SiteTree relates to until AFTER it's queried, by which it's too late to rewrite the query.

The best you could do is use a non-translated dataobject for your news articles, and link to it from your newsarticle holder.
