### ISSUE TITLE
no visual indication in which locale user is editing content

### ISSUE THREAD

**Issue by guyvanbael** [tractorcow/silverstripe-fluent#311]
in version 3.8 users could easily see in which locale they were editing contect.
Version 4 has no visual aid.
And also... the locale isn't added to the urlsegment, so the link is wrong.
<img width="488" alt="schermafbeelding 2017-11-29 om 14 39 18" src="https://user-images.githubusercontent.com/3098809/33378006-b57d931c-d513-11e7-87f7-f219e87122c1.png">

**Comment by tractorcow** [comment]
Thanks we can fix the preview link without too much trouble, I believe.

The "current locale" message is still being migrated I believe from the old fluent. We aren't 100% certain it'll be the same as it used to be.

**Comment by robbieaverill** [comment]
Note: Use Bootstrap classes (`.alert.alert-warning`/`.alert-info`) instead of `.message.warning` for example, since they're being removed

**Comment by tractorcow** [comment]
Sorry this should have been on the roadmap for upgrade. I've added this now https://github.com/tractorcow/silverstripe-fluent/issues/261

**Comment by raissanorth** [comment]
The issue regarding the current local message is addressed in https://github.com/tractorcow/silverstripe-fluent/pull/343

**Comment by robbieaverill** [comment]
Nice @raissanorth! I've logged the other issue at https://github.com/tractorcow/silverstripe-fluent/issues/344 and will tackle it now

**Comment by robbieaverill** [comment]
@tractorcow - @clarkepaul came up with some cool designs today for a more accurate way of communicating the locale the content exists in, which is potentially more relevant than the Fluent 3 alert message - since we now have inherited pages that are visible on the frontend (if using fallback locales) and invisible pages that can still be copied through to make them owned by and visible in the current locale (if using exclusive locales).

We had a couple of questions for you though:

* If I have en_GB as my default locale, en_NZ as another that falls back to en_GB and de_DE as an exclusive locale that doesn't fallback, I expect to see en_GB owned pages in the sitetree (greyed out) when I'm viewing it in the en_NZ locale. I should also expect to see en_GB pages in the sitetree when editing in de_DE, but should I expect to see en_NZ pages when editing in de_DE?

* How do non-translated fields fall back? E.g. if I translate all page fields except for Content (for example), does the content value get read from the default locale always? Can I modify that default value when changing the Content in a non-default locale too, like in Fluent 3?

**Comment by tractorcow** [comment]
> but should I expect to see en_NZ pages when editing in de_DE?

Items aren't hidden in the tree in specific locales.

> How do non-translated fields fall back? E.g. if I translate all page fields except for Content (for example), does the content value get read from the default locale always? Can I modify that default value when changing the Content in a non-default locale too, like in Fluent 3?

You can't translate only partial fields because the localisation is a complete row. You'd end up with a localised empty Content field, if you tried to leave it blank.

**Comment by robbieaverill** [comment]
Ok so just to clarify:

>Items aren't hidden in the tree in specific locales.

So in all locales, regardless of whether they fallback to each other and including the default locale, you'll always see all available pages from all locales.

>You can't translate only partial fields because the localisation is a complete row. You'd end up with a localised empty Content field, if you tried to leave it blank.

So what happens if I make a File fluent and set `translate: [Title]` - do the rest of its fields become empty? If so, do we need to make it clear in the docs that you don't need to use the `translate` configuration and just having added fluent to the DataObject is enough?

**Comment by clarkepaul** [comment]
Mockups created here for reference. https://invis.io/ZBFVZJCKU38#/279729292_X_Fluent

**Comment by robbieaverill** [comment]
Summary:

* Localised URL segment fixed in https://github.com/tractorcow/silverstripe-fluent/issues/344
* Current locale indicator added with #362 in the CMS breadcrumbs
* Bootstrap alert for invisible content in the current locale added/updated in #361
* Translatable icon for translatable form fields (requires SS 4.1.0 [unreleased]) in #366
