### ISSUE TITLE
Error at line 64 of */framework/model/connect/DBConnector.php

### ISSUE THREAD

**Issue by gongo-a** [tractorcow/silverstripe-fluent#357]
When installing the platform of silverstripe I gave errors after the directory / install I have accessed the root folder by web and I get an error on line 64, saying:

[Emergency] Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query: SHOW DATABASES LIKE '(name_of-database)' 42000-1227: Access denied; you need (at least one of) the SHOW DATABASES privilege(s) for this operation

`Line 64 in /home/vol15_1/byethost15.com/b15_21635994/htdocs/vendor/silverstripe/framework/src/ORM/Connect/DBConnector.php`

> 55         if (!empty($sql)) {
56             $formatter = new SQLFormatter();
57             $formattedSQL = $formatter->formatPlain($sql);
58             $msg = "Couldn't run query:\n\n{$formattedSQL}\n\n{$msg}";
59         }
60 
61         if ($errorLevel === E_USER_ERROR) {
62             // Treating errors as exceptions better allows for responding to errors
63             // in code, such as credential checking during installation
64             throw new DatabaseException($msg, 0, null, $sql, $parameters);
65         } else {
66             user_error($msg, $errorLevel);
67         }
68     }
69 
70     /**

What is the problem?

PD: I'm sorry for not using GitHub correctly and the faults that it contains, it's my first day

**Comment by robbieaverill** [comment]
Hi @gongo-a 

This error indicates that the user you're using to connect to your database doesn't have sufficient privileges to do what it needs to do to install SilverStripe.

I suggest for local development you start by using a "root" user, or a user with all permissions granted to it (i.e. `GRANT ALL ON your_ss_db.* to 'youruser'@'%';` for example on MySQL).

Closing since this isn't a Fluent bug.

Feel free to ask for more help in the [community Slack channel](https://www.silverstripe.org/community/slack-signup/) or on [StackOverflow](https://stackoverflow.com/questions/tagged/silverstripe) =)

**Comment by gongo-a** [comment]
Hi @robbieaverill 

In that case, since the count would have to change the permit? In the same code? In the PHPMyAdmin panel?

It is not a local installation therefore I do not have root privileges. What would be the solution?

Thank you very much for your help!

**Comment by dhensby** [comment]
@gongo-a this isn't a SilverStripe problem, it's a database configuration issue and it'd be best that you search another resource for more help as you'll find better resources on websites dedicated to setting up a database (and their users) via PHPMyAdmin
