### ISSUE TITLE
Nullable fields?

### ISSUE THREAD

**Issue by mmitranic** [tractorcow/silverstripe-fluent#399]
Empty localised fields return the last saved locale's value instead of null.

This was solved in Fluent 3 by using $nullable_fields. Are there any plans to implement this feature in Fluent 4?

**Comment by tractorcow** [comment]
It won't work the same way, because fluent 4 fields are nullable by default, but you must save in at least one locale.

Unless you have `frontend_publish_required` set to false (I recommend you leave it true) then the row won't be visible at all on the frontend until you publish.

If you really need to control the individual fallback of specific fields you can implement `updateLocaliseSelectDefault` in your class and set it to null.

**Comment by RoyalPulp** [comment]
Oh Noooooooooo !
Just really needed that feature , but I had to set frontend_publish_required to false, according to solving that problem: https://github.com/tractorcow-farm/silverstripe-fluent/issues/686

I think most really important thing would be a good, complete documentation for Fluent!!! Also for the differences between the old (SS3) and new (SS4) version!!
